steps:
    
- id: go_test
  name: 'golang'
  args: ['go','test']

  #Gerar imagem 
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'version=1.0.0'
    - '-t'
    - 'gcr.io/$PROJECT_ID/DesafioCI:latest'
    - '-t'
    - 'gcr.io/$PROJECT_ID/DesafioCI:1.24.0'
    - '.'
- name: 'gcr.io/$PROJECT_ID/DesafioCI'
  args: ['version']
    
images:
- 'gcr.io/$PROJECT_ID/DesafioCI:latest'
- 'gcr.io/$PROJECT_ID/DesafioCI:1.0.0'
