steps:
- id: go_version
  name: 'golang'
  args: ['go','version']

- id: go_test
  name: 'golang'
  args: ['go','test']

- id: mostrando arquivo
  name: "golang"
  args: ['ls']

- id: mostrando diretorio
  name: "golang"
  args: ['pwd']