steps:
    
- id: go_test
  name: 'golang'
  args: ['go','test']

# - id: Gerando Imagem
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','--build-args','version=latest','-t','gcr.io/$PROJECT_ID/desafioCI','.']
images: ['gcr.io/$PROJECT_ID/desafioCI:latest']
